name: 'Test Action'
description: 'Runs a simple execution to validate compiled built deliverable'
author: 'attendee'
inputs:
  artifact-version: # semantic version of the artifact from build
    description: 'built version of artifact'
    required: true
    default: '1.0.0'
  arguments-to-print: # rest of arguments to echo out
    description: 'arguments to print out'
runs:
  using: "composite"
  steps:
    - name: Download candidate artifacts
      uses: actions/download-artifact@v3
      with:
        name: greetings-jar
    - id: test-run
      env: 
        ARGS: ${{ inputs.arguments-to-print }}
      run: |
        chmod +x ${{ github.action_path }}/test-script.sh
        ${{ github.action_path }}/test-script.sh ${{ inputs.artifact-version }} "$ARGS"
      shell: bash

# 로컬 액션 사용법:
# - uses: actions/checkout@v4
# - name: run-test
#   uses: ./.github/actions/test-action # yml이 아니라 폴더를 지정
#   with:
#     artifact-version: ${{ needs.build.outputs.artifact-tag || github.event.inputs.myVersion }}
#     arguments-to-print: ${{ github.event.inputs.myValues }}