name: count_args_action_example
# 이 액션은 custom action인 argument_count_example를 사용하는 예제
on:
  workflow_dispatch:
    inputs:
      myValues: # 인수 여러개를 워크플로우 시작 시 입력한다.
        description: 'Input Values'

jobs:
  count-args:
    runs-on: ubuntu-latest
    steps:
    - id: report-count
      uses: openLeeWorld/arg_count_action_example@main # 액션 리포지토리 참조 (github.com 기준)
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }} 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }}

  count-args-docker:
    runs-on: ubuntu-latest
    steps:
    - id: report-count-docker
      uses: openLeeWorld/Dockerfile_CustomAction_practice@main # 액션 리포지토리 참조 (github.com 기준)
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }} 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count-docker.outputs.arg-count }}

  count-args-js:
    runs-on: ubuntu-latest
    steps:
    - id: report-count-js
      uses: openLeeWorld/js_custom_action_practice@main # 액션 리포지토리 참조 (github.com 기준)
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }} 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count-js.outputs.argCount }}
