name: environment_var

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF == 'true'}} 
    # if 구문이 true가 되야 jobs가 실행됨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ -f ${{ vars.FILE_TO_CHECK }}]]; then  
            echo "${{ vars.FILE_TO_CHECK }} files needs to be added to ${{ github.repository }} !" 
            exit 1  
          fi   

