name: shell_practice

on:
  push:
    branches:
      - shell_practice

defaults:
  run:
    shell: bash
    working-directory: workdir # workflow 기본 디렉토리
# 잡 설정과 워크플로우 설정에서 모두 기본값을 정의하면, 잡 설정의 기본값이 우선됩니다.
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        #working-directory: {{ github.workspace }} # 체크아웃한 저장소의 루트 디렉토리
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p test # 디렉토리가 존재하지 않으면 생성 후 실행
      - run: echo "in test"
        working-directory: test
        
